# Generated by Django 2.0.2 on 2018-03-22 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Checkout Out')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Checked In')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('relative_location', models.CharField(max_length=100)),
                ('site', models.CharField(choices=[('Storage Unit', 'Storage Unit'), ('NSP Office', 'NSP Office')], max_length=1)),
                ('tech_classification', models.CharField(choices=[('Technology', 'Technology'), ('Not Technology', 'Not Technology')], max_length=30)),
                ('checkoutable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorydata.Item'),
        ),
    ]
