# Generated by Django 2.0.2 on 2018-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='site',
            field=models.CharField(choices=[('Storage Unit', 'Storage Unit'), ('NSP Office', 'NSP Office')], max_length=30),
        ),
    ]
